### ISSUE TITLE
Add movies category screen XML layout

### ISSUE THREAD

**Issue by YassinAJDI** [YassinAJDI/aad-team-29-animation-challenge#3]
- When user clicks a category in homepage #2 This view get updated correctly and will display movies for that category

**Comment by amnsabir** [comment]
hello yassin i will work on that issue

**Comment by gharras** [comment]
ok it's yours

**Comment by YassinAJDI** [comment]
@amnsabir glad you found something you like 👍

**Comment by amnsabir** [comment]
thank you guys
